export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const REGISTER = "REGISTER";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_DRIVERS = "FETCH_DRIVERS";
export const DELETE_OPERATOR = "DELETE_OPERATOR";
export const REGISTER_EMPLOYEES_FAIL = "REGISTER_EMPLOYEES_FAIL";
export const SHOW_MODAL = "SHOW_MODAL";
export const SHOW_OPERATOR_MODAL = "SHOW_OPERATOR_MODAL";
export const SHOW_DRIVER_MODAL = "SHOW_DRIVER_MODAL";
export const UPDATE_OPERATOR = "UPDATE_OPERATOR";
export const FETCH_BUSES = "FETCH_BUSES";
export const REGISTER_BUS = "REGISTER_BUS";
export const REGISTER_BUS_FAIL = "REGISTER_BUS_FAIL";
export const DELETE_BUS = "DELETE_BUS";
export const UPDATE_BUS = "UPDATE_BUS";
export const UPDATE_BUS_FAIL = "UPDATE_BUS_FAIL";
export const SHOW_BUS_MODAL = "SHOW_BUS_MODAL";
export const UPDATE_DRIVER = "UPDATE_DRIVER";
export const UPDATE_OPERATOR_FAIL = "UPDATE_OPERATOR_FAIL";
// MODALS
export const SHOW_ROLE_MODAL = "SHOW_ROLE_MODAL";
export const SHOW_PERMISSION_MODAL = "SHOW_PERMISSION_MODAL";
// ROLE ACTION TYPES
export const FETCH_ROLES = "FETCH_ROLES";
export const CREATE_ROLES = "CREATE_ROLES";
export const UPDATE_ROLES = "UPDATE_ROLES";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const DELETE_ROLES = "DELETE_ROLES";
export const HANDLE_ROLES_ERRORS = "HANDLE_ROLES_ERRORS";
// PERMISSION ACTION TYPES
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const CREATE_PERMISSIONS = "CREATE_PERMISSIONS";
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";
export const UPDATE_PERMISSION_FAIL = "UPDATE_PERMISSION_FAIL";
export const DELETE_PERMISSIONS = "DELETE_PERMISSIONS";
export const HANDLE_PERMISSIONS_ERRORS = "HANDLE_PERMISSIONS_ERRORS";


export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const LOADING_ACTION = "LOADING_ACTION";
export const SHOW_ASSIGN_MODAL = "SHOW_ASSIGN_MODAL";
export const ASSIGN_BUS_SUCCESS = "ASSIGN_BUS_SUCCESS";
export const ASSIGN_BUS_FAIL = "ASSIGN_BUS_FAIL";
export const FETCH_DRIVERS_ASSIGNED_BUSES = "FETCH_DRIVERS_ASSIGNED_BUSES";
export const UNASSIGN_DRIVER_FROM_BUS = "UNASSIGN_DRIVER_FROM_BUS";
export const FETCH_OPERATORS = "FETCH_OPERATORS";


// UPDATE PROFILE
export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SHOW_PROFILE_MODAL = "SHOW_PROFILE_MODAL";




/* =============================================
This is where all our action types constants 
are defined
============================================== */

