export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const REGISTER = "REGISTER";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_DRIVERS = "FETCH_DRIVERS";
export const DELETE_OPERATOR = "DELETE_OPERATOR";
export const REGISTER_EMPLOYEES_FAIL = "REGISTER_EMPLOYEES_FAIL";
export const SHOW_MODAL = "SHOW_MODAL";
export const SHOW_OPERATOR_MODAL = "SHOW_OPERATOR_MODAL";
export const SHOW_DRIVER_MODAL = "SHOW_DRIVER_MODAL";
export const UPDATE_OPERATOR = "UPDATE_OPERATOR";
export const UPDATE_DRIVER = "UPDATE_DRIVER";
export const UPDATE_OPERATOR_FAIL = "UPDATE_OPERATOR_FAIL";
// MODALS
export const SHOW_ROLE_MODAL = "SHOW_ROLE_MODAL";
export const SHOW_PERMISSION_MODAL = "SHOW_PERMISSION_MODAL";
// ROLE ACTION TYPES
export const FETCH_ROLES = "FETCH_ROLES";
export const CREATE_ROLES = "CREATE_ROLES";
export const UPDATE_ROLES = "UPDATE_ROLES";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const DELETE_ROLES = "DELETE_ROLES";
export const HANDLE_ROLES_ERRORS = "HANDLE_ROLES_ERRORS";
// PERMISSION ACTION TYPES
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const CREATE_PERMISSIONS = "CREATE_PERMISSIONS";
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";
export const UPDATE_PERMISSION_FAIL = "UPDATE_PERMISSION_FAIL";
export const DELETE_PERMISSIONS = "DELETE_PERMISSIONS";
export const HANDLE_PERMISSIONS_ERRORS = "HANDLE_PERMISSIONS_ERRORS";

export const FETCH_OPERATORS = "FETCH_OPERATORS";


// UPDATE PROFILE
export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SHOW_PROFILE_MODAL = "SHOW_PROFILE_MODAL";




/* =============================================
This is where all our action types constants 
are defined
============================================== */


